version: '3'

services:
  openvpn:
    build:
      context: .
      dockerfile: Dockerfile.openvpn
    image: openvpn:local
    command: /etc/openvpn/setup/configure.sh
    environment:
      OVPN_SERVER_NET: "192.168.100.0"
      OVPN_SERVER_MASK: "255.255.255.0"
      OVPN_PASSWD_AUTH: "true"
    cap_add:
      - NET_ADMIN
    ports:
      - 11194:1194 # for openvpn
      # - 11195:8080 # for ovpn-admin because of network_mode
    volumes:
      - ./easyrsa_master:/etc/openvpn/easyrsa
      - ./ccd_master:/etc/openvpn/ccd
  ovpn-admin:
    build:
      context: .
    image: ovpn-admin:local
    command: /app/ovpn-admin
    environment:
      OVPN_DEBUG: "True"
      OVPN_VERBOSE: "True"
      OVPN_NETWORK: "192.168.100.0/24"
      EASYRSA_PATH: "/mnt/easyrsa"
      OVPN_SERVER: "127.0.0.1:7777:tcp"
      OVPN_INDEX_PATH: "/mnt/easyrsa/pki/index.txt"
      OVPN_AUTH: "True"
      OVPN_AUTH_DB_PATH: "/mnt/easyrsa/pki/users.db"
    network_mode: service:openvpn
    volumes:
      - ./easyrsa_master:/mnt/easyrsa
      - ./ccd_master:/mnt/ccd
  nginx:
    image: 'nginx'
    ports:
      - '11195:80'
    links:
      - 'openvpn'
    volumes:
      - './nginx/default.conf:/etc/nginx/conf.d/default.conf'
      - './nginx/.htpasswd:/etc/nginx/.htpasswd'